//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_Topup
    {
        public long ID { get; set; }
        public string User_ID { get; set; }
        public string Price { get; set; }
        public string Sim { get; set; }
        public string Net { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Message { get; set; }
        public string Note { get; set; }
    }
}
